# ruff: noqa: E501
# Feature: go-analyzer-support, Property 1: Vendor directories never contribute detections.
"""Property test for the vendor-directory exclusion (Requirement 1.3).

**Validates Requirements 1.3** (Property 1 in the design, task 11.7 in
``tasks.md``).

The vendor exclusion is implemented at the aggregator boundary in
:func:`project_knowledge_mcp.project_analyzer.go.go_filter.is_go_source_file`
and is the single place the four Go sub-analyzers depend on for
filtering vendored copies of third-party libraries. Per design §3
"Vendor-Directory Exclusion", any repository path containing a
directory segment equal to ``vendor`` (case-sensitive, after
normalizing ``\\`` to ``/``) is rejected before reaching the
tokenizer, so a vendored copy of a Go source file cannot contribute
to any of the four detection sections of a
:class:`~project_knowledge_mcp.models.ProjectProfile`.

This property exercises the full :func:`analyze` pipeline end-to-end
across the four Go sub-analyzers (purpose summarizer, I/O extractor,
external service detector, database table detector) on synthetic
repositories that mix:

* Non-vendor Go source files that exercise every recognizer with
  patterns drawn verbatim from the four sample repositories
  (``http.HandleFunc``, ``mux.Handle``, ``cron.New``/``AddFunc``,
  ``activemq``'s ``Subscribe`` and ``SendMessage`` shapes with
  ``domain.SubscriberConfig`` and ``domain.Message`` composite
  literals, ``os.Open``/``os.WriteFile``, ``fec_pool_service/pb``'s
  ``ExecuteQuery`` and ``esb-go-libs/dbadapter``'s
  ``PoolExecuteQuery``, the ``activemq.NewClient`` broker setup).
* Identical sources placed under a ``vendor/`` directory using the
  four shapes recognized as vendored by the design: top-level
  ``vendor/``, deeply-nested ``vendor/github.com/...``,
  ``vendor/example.com/.../v2/`` semver-suffixed paths, and
  mid-path ``internal/vendor/`` (every shape the unit test
  :mod:`tests.unit.test_go_filter` covers).

Two related properties are checked:

1. **No detection references a vendored path.** For every entry in
   :attr:`ProjectProfile.external_service_dependencies` and every
   entry in :attr:`ProjectProfile.database_table_dependencies`, every
   :class:`SourceLocation`'s ``path`` MUST NOT contain a ``vendor``
   directory segment. For every :class:`AbstractInput` and every
   :class:`AbstractOutput`, the ``description`` MUST NOT contain the
   string form of any vendored path generated by the test (the four
   Go I/O recognizers encode the source-file path into the
   description as an ``at <path>:<line>`` suffix, so a leaked
   vendored path would surface as a substring match).

2. **Adding vendor copies is inert.** Given any non-vendor Go
   repository, adding a duplicate of every Go source file under a
   ``vendor/<subtree>/`` prefix MUST NOT change any of the four
   detection lists or the ``degraded_sections`` list of the produced
   :class:`ProjectProfile`. This is the "copying a non-vendor file
   under ``vendor/`` produces no additional detection" formulation
   from task 11.7's optional refinement.

Both properties are end-to-end against :func:`analyze` so the test
exercises the same call path production traffic takes. The
sub-analyzer-internal predicate :func:`is_go_source_file` is unit
tested separately (Task 2.2, :mod:`tests.unit.test_go_filter`); this
property pins the aggregator's *use* of that predicate as the only
filter the four sub-analyzers depend on for vendor exclusion.
"""

from __future__ import annotations

from typing import Final

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from project_knowledge_mcp.models import RepositoryContents
from project_knowledge_mcp.project_analyzer import analyze

pytestmark = pytest.mark.property


# ---------------------------------------------------------------------------
# Detection-producing snippet catalogue
# ---------------------------------------------------------------------------
#
# Each entry pairs a file-name suffix with a self-contained Go source
# fragment that exercises one detection path documented in the design.
# The fragments are intentionally minimal: every fragment uses only the
# constructs the analyzer's tokenizer and construct recognizer support
# (imports, package declaration, function declarations, method calls,
# composite literals with named-field syntax, string literals), and
# every fragment includes the smallest set of imports and call shapes
# the relevant recognizer requires.
#
# The fragments are drawn from the canonical patterns recorded in the
# four sample repositories named in the requirements document, so a
# regression that breaks vendor exclusion for any one recognizer
# surfaces immediately on the property's first counter-example.

#: HTTP route registration on the default ``http.ServeMux`` (Requirement
#: 3.2 first bullet, package-level ``http.HandleFunc`` shape observed
#: in ``repayment_service``).
_HTTP_DEFAULT_MUX_SOURCE: Final[str] = (
    'package svc\n'
    'import "net/http"\n'
    '\n'
    'func register() {\n'
    '\thttp.HandleFunc("/users", nil)\n'
    '}\n'
)


#: HTTP route registration on an ``http.NewServeMux()`` receiver
#: (Requirement 3.2 second bullet, single-identifier-receiver
#: relaxation in any file importing ``net/http``).
_HTTP_MUX_RECEIVER_SOURCE: Final[str] = (
    'package svc\n'
    'import "net/http"\n'
    '\n'
    'func register(mux *http.ServeMux) {\n'
    '\tmux.Handle("/healthz", nil)\n'
    '}\n'
)


#: ``cron.New(cron.WithSeconds())`` constructor followed by an
#: ``AddFunc(<schedule>, h)`` registration (Requirement 4.2 first two
#: bullets, six-field schedule shape observed in ``cat-service``).
_CRON_SCHEDULER_SOURCE: Final[str] = (
    'package svc\n'
    'import "github.com/robfig/cron/v3"\n'
    '\n'
    'func register() {\n'
    '\tc := cron.New(cron.WithSeconds())\n'
    '\tc.AddFunc("0 0 * * * *", nil)\n'
    '}\n'
)


#: ActiveMQ subscription via the in-house wrapper (Requirement 5.3
#: first bullet; ``domain.SubscriberConfig`` shape observed in
#: ``aps_los_vtiger``).
_ACTIVEMQ_SUBSCRIBE_SOURCE: Final[str] = (
    'package svc\n'
    'import (\n'
    '\t"context"\n'
    '\t"esb-go-libs/activemq/domain"\n'
    ')\n'
    '\n'
    'func sub(ctx context.Context, recv interface{}) {\n'
    '\trecv.Subscribe(ctx, nil, &domain.SubscriberConfig{Destination: "Q.INBOUND"}, nil)\n'
    '}\n'
)


#: ActiveMQ publication via the in-house wrapper (Requirement 5.3
#: second bullet; ``domain.Message`` shape observed in
#: ``repayment_service``).
_ACTIVEMQ_PUBLISH_SOURCE: Final[str] = (
    'package svc\n'
    'import (\n'
    '\t"context"\n'
    '\t"esb-go-libs/activemq/domain"\n'
    ')\n'
    '\n'
    'func send(ctx context.Context, sender interface{}) {\n'
    '\tsender.SendMessage(ctx, "tx", "corr", &domain.Message{Destination: "Q.OUTBOUND"})\n'
    '}\n'
)


#: File I/O recognizer: ``os.Open`` (input) and ``os.WriteFile``
#: (output), Requirements 6.1 and 6.2.
_FILE_IO_SOURCE: Final[str] = (
    'package svc\n'
    'import "os"\n'
    '\n'
    'func work() {\n'
    '\t_, _ = os.Open("config.json")\n'
    '\t_ = os.WriteFile("out.log", nil, 0644)\n'
    '}\n'
)


#: ActiveMQ broker connection setup (Requirement 8.5; the broker host
#: is the external-service site, the call itself contributes no I/O
#: entry per Requirement 5.3 third bullet).
_ACTIVEMQ_BROKER_SOURCE: Final[str] = (
    'package svc\n'
    'import "esb-go-libs/activemq"\n'
    '\n'
    'func setup() {\n'
    '\t_ = activemq.NewClient(&activemq.JmsConfig{BrokerUrl: "tcp://broker.example.com:61616"})\n'
    '}\n'
)


#: ``fec_pool_service/pb`` external service (Requirement 8.2; the
#: canonical Oracle gateway shape used by every other Go service in
#: the organization).
_FEC_POOL_PB_SOURCE: Final[str] = (
    'package svc\n'
    'import (\n'
    '\t"context"\n'
    '\tpb "fec_pool_service/pb"\n'
    ')\n'
    '\n'
    'func q(ctx context.Context, c pb.PoolAPIClient) {\n'
    '\t_, _ = c.ExecuteQuery(ctx, &pb.PoolExecuteQueryRequest{QueryString: "SELECT id FROM USERS"})\n'
    '}\n'
)


#: ``esb-go-libs/dbadapter`` plus a literal SQL statement in a
#: ``model.PoolServiceRequest`` composite literal (Requirements 9.1,
#: 9.2; the adapter path used by three of the four sample
#: repositories).
_DB_TABLE_SOURCE: Final[str] = (
    'package svc\n'
    'import (\n'
    '\t"context"\n'
    '\t"esb-go-libs/dbadapter"\n'
    '\t"esb-go-libs/dbadapter/model"\n'
    ')\n'
    '\n'
    'func q(ctx context.Context, a dbadapter.IPoolAPIAdapter) {\n'
    '\t_, _ = a.PoolExecuteQuery(ctx, &model.PoolServiceRequest{QueryString: "INSERT INTO ORDERS VALUES (1)"}, "u", "p")\n'
    '}\n'
)


#: Catalogue mapping a stable suffix to each detection-producing
#: source fragment. The suffix is the file's basename; the
#: enclosing directory is chosen by the placement strategy below.
_DETECTION_SNIPPETS: Final[tuple[tuple[str, str], ...]] = (
    ("http_default.go", _HTTP_DEFAULT_MUX_SOURCE),
    ("http_mux.go", _HTTP_MUX_RECEIVER_SOURCE),
    ("scheduler.go", _CRON_SCHEDULER_SOURCE),
    ("subscribe.go", _ACTIVEMQ_SUBSCRIBE_SOURCE),
    ("publish.go", _ACTIVEMQ_PUBLISH_SOURCE),
    ("files.go", _FILE_IO_SOURCE),
    ("broker.go", _ACTIVEMQ_BROKER_SOURCE),
    ("pool.go", _FEC_POOL_PB_SOURCE),
    ("tables.go", _DB_TABLE_SOURCE),
)


# ---------------------------------------------------------------------------
# Placement strategies
# ---------------------------------------------------------------------------
#
# A "placement" is a directory prefix that ``is_go_source_file``
# either accepts (non-vendor) or rejects (any path containing a
# ``vendor`` directory segment). The four non-vendor prefixes
# correspond to the directory layouts observed in the four sample
# repositories: a flat ``internal/`` tree, an explicit ``pkg/``
# layout, a ``cmd/<binary>/`` entry-point tree, and a ``service/``
# subpackage tree. The four vendor prefixes correspond to the four
# shapes the design's vendor predicate must reject: top-level
# ``vendor/``, deeply-nested ``vendor/github.com/...``,
# ``vendor/example.com/lib/v2/`` semver suffix, and the
# mid-path ``internal/vendor/`` case (every shape pinned by
# :mod:`tests.unit.test_go_filter`).

#: Non-vendor directory prefixes. ``is_go_source_file`` accepts paths
#: with any of these prefixes provided no enclosing segment equals
#: ``vendor``. The empty string represents a root-level placement,
#: which the design's CLI recognizer treats specially only when the
#: file is named ``main.go`` (which none of the snippet suffixes
#: above are).
_NON_VENDOR_PREFIXES: Final[tuple[str, ...]] = (
    "",
    "internal/",
    "pkg/handlers/",
    "cmd/svc/",
    "service/",
)


#: Vendor directory prefixes. Every prefix here contains a directory
#: segment equal to ``vendor``, so ``is_go_source_file`` rejects every
#: path that gets one of these prefixes. The set covers top-level
#: ``vendor/``, deeply-nested ``vendor/<host>/<org>/<lib>/``, a
#: semver-suffixed ``vendor/<host>/<org>/<lib>/v2/`` form, and the
#: mid-path ``internal/vendor/`` shape pinned by
#: :func:`tests.unit.test_go_filter.test_is_go_source_file_rejects_vendor_segment_in_middle_of_path`.
_VENDOR_PREFIXES: Final[tuple[str, ...]] = (
    "vendor/",
    "vendor/github.com/pkg/errors/",
    "vendor/example.com/lib/v2/",
    "internal/vendor/foo/",
)


# ---------------------------------------------------------------------------
# Vendor-segment predicate (mirror of the production filter)
# ---------------------------------------------------------------------------


def _path_has_vendor_segment(path: str) -> bool:
    """Return ``True`` when any directory segment of ``path`` equals
    ``vendor``.

    Mirrors the rejection rule applied by
    :func:`project_knowledge_mcp.project_analyzer.go.go_filter.is_go_source_file`
    so the property's assertion is independent of that helper's
    implementation. Path separators are normalized to ``/`` before
    splitting; the file's basename is excluded from the directory
    inspection so a file literally named ``vendor.go`` is not
    misclassified.
    """

    normalized = path.replace("\\", "/")
    parts = normalized.split("/")
    return "vendor" in parts[:-1]


# ---------------------------------------------------------------------------
# Hypothesis strategies
# ---------------------------------------------------------------------------


@st.composite
def _mixed_placement_repo(
    draw: st.DrawFn,
) -> tuple[dict[str, str], frozenset[str]]:
    """Generate a Go repo whose files mix vendored and non-vendored paths.

    Returns a ``(files, vendor_paths)`` pair where:

    * ``files`` is the :class:`RepositoryContents.files` mapping.
    * ``vendor_paths`` is the set of file paths in ``files`` whose
      enclosing directories include a ``vendor`` segment. Used by the
      assertion path to substring-match every emitted description and
      every emitted source-location path against the concrete vendor
      file set this example actually contains.

    Each generated file's basename is prefixed with a unique sequence
    index ``f{idx}_`` so collisions across draws are impossible —
    every snippet can be drawn any number of times and the resulting
    paths remain distinct.
    """

    all_prefixes = _NON_VENDOR_PREFIXES + _VENDOR_PREFIXES
    placements = draw(
        st.lists(
            st.tuples(
                st.integers(min_value=0, max_value=len(_DETECTION_SNIPPETS) - 1),
                st.sampled_from(all_prefixes),
            ),
            min_size=0,
            max_size=8,
        ),
    )

    files: dict[str, str] = {}
    vendor_paths: set[str] = set()
    for idx, (snippet_idx, prefix) in enumerate(placements):
        suffix, source = _DETECTION_SNIPPETS[snippet_idx]
        path = f"{prefix}f{idx}_{suffix}"
        files[path] = source
        if _path_has_vendor_segment(path):
            vendor_paths.add(path)
    return files, frozenset(vendor_paths)


@st.composite
def _non_vendor_only_repo(draw: st.DrawFn) -> dict[str, str]:
    """Generate a Go repo whose files all sit at non-vendor paths.

    Used as the baseline for the "adding vendor copies is inert"
    refinement: the test duplicates every Go source under a
    ``vendor/<subtree>/`` prefix and asserts the produced
    :class:`ProjectProfile` is unchanged across the two analyses.
    """

    placements = draw(
        st.lists(
            st.tuples(
                st.integers(min_value=0, max_value=len(_DETECTION_SNIPPETS) - 1),
                st.sampled_from(_NON_VENDOR_PREFIXES),
            ),
            min_size=0,
            max_size=6,
        ),
    )

    files: dict[str, str] = {}
    for idx, (snippet_idx, prefix) in enumerate(placements):
        suffix, source = _DETECTION_SNIPPETS[snippet_idx]
        path = f"{prefix}f{idx}_{suffix}"
        files[path] = source
    return files


# ---------------------------------------------------------------------------
# Shared analyze() invocation
# ---------------------------------------------------------------------------


def _run_analyze(files: dict[str, str]) -> object:
    """Run :func:`analyze` against ``files`` with fixed identity fields.

    Keeping the identity fields (``project_id``, ``full_path``,
    ``analysis_branch``, ``commit_sha``, ``repo_description``) fixed
    across calls means that any difference observed between two
    analyses on different file sets is attributable to the file
    contents alone. The commit SHA is the conventional all-zero
    placeholder used by other property tests in this suite.
    """

    rc = RepositoryContents(
        gitlab_project_id=1,
        commit_sha="0" * 40,
        files=files,
    )
    return analyze(
        project_id=1,
        full_path="group/vendor-exclusion-test",
        analysis_branch="main",
        commit_sha="0" * 40,
        repo_description=None,
        repository_contents=rc,
    )


# ---------------------------------------------------------------------------
# Property 1A: No detection references a vendored path
# ---------------------------------------------------------------------------


@given(spec=_mixed_placement_repo())
@settings(
    max_examples=50,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)
def test_no_detection_references_a_vendored_path(
    spec: tuple[dict[str, str], frozenset[str]],
) -> None:
    """For every mixed-placement repo, no detection cites a vendored file.

    Validates Requirement 1.3: a Go source file under any directory
    segment named ``vendor`` SHALL NOT contribute to any detection in
    the produced :class:`ProjectProfile`. The property is checked
    against the full :func:`analyze` pipeline so a regression in any
    of the four sub-analyzers' dispatch surfaces immediately.
    """

    files, vendor_paths = spec
    profile = _run_analyze(files)

    # ------------------------------------------------------------------
    # External service dependencies: every source location must be
    # vendor-free, and none may match a file the test itself placed
    # under a vendor directory. The first check is the strong
    # invariant (a regression that leaks any vendor path, not just one
    # we generated, surfaces here); the second check is the targeted
    # check (a regression that happens to match a vendor path we
    # generated surfaces with the offending path named).
    # ------------------------------------------------------------------
    for service in profile.external_service_dependencies:
        for loc in service.source_locations:
            assert not _path_has_vendor_segment(loc.path), (
                f"external service {service.name!r} has source_location "
                f"path {loc.path!r} containing a 'vendor' directory "
                f"segment (Requirement 1.3)"
            )
            assert loc.path not in vendor_paths, (
                f"external service {service.name!r} cites generated "
                f"vendor file {loc.path!r}; vendor files must not "
                f"contribute detections (Requirement 1.3)"
            )

    # ------------------------------------------------------------------
    # Database table dependencies: same contract.
    # ------------------------------------------------------------------
    for table in profile.database_table_dependencies:
        for loc in table.source_locations:
            assert not _path_has_vendor_segment(loc.path), (
                f"database table {table.table_name!r} has "
                f"source_location path {loc.path!r} containing a "
                f"'vendor' directory segment (Requirement 1.3)"
            )
            assert loc.path not in vendor_paths, (
                f"database table {table.table_name!r} cites generated "
                f"vendor file {loc.path!r}; vendor files must not "
                f"contribute detections (Requirement 1.3)"
            )

    # ------------------------------------------------------------------
    # Abstract inputs and outputs: the four Go I/O recognizers encode
    # the source-file path into the description as an
    # ``at <path>:<line>`` suffix (or, for HTTP placeholder
    # descriptions, ``<dynamic at <path>:<line> on <recv>>``). A
    # vendored path that slipped through would surface as a substring
    # match against the concrete vendor files we generated. The
    # substring check is targeted (it can produce false negatives if
    # the recognizer used a different path encoding, but the
    # ``loc.path`` checks above pin the source-location-bearing
    # detection types). Together the two checks rule out every
    # observable leak.
    # ------------------------------------------------------------------
    for entry in profile.abstract_inputs:
        for vp in vendor_paths:
            assert vp not in entry.description, (
                f"abstract_input description {entry.description!r} "
                f"references generated vendor file {vp!r}; vendor "
                f"files must not contribute detections "
                f"(Requirement 1.3)"
            )
    for entry in profile.abstract_outputs:
        for vp in vendor_paths:
            assert vp not in entry.description, (
                f"abstract_output description {entry.description!r} "
                f"references generated vendor file {vp!r}; vendor "
                f"files must not contribute detections "
                f"(Requirement 1.3)"
            )


# ---------------------------------------------------------------------------
# Property 1B: Adding vendor copies is inert
# ---------------------------------------------------------------------------


@given(base_files=_non_vendor_only_repo())
@settings(
    max_examples=30,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)
def test_adding_vendor_copies_does_not_change_detections(
    base_files: dict[str, str],
) -> None:
    """Refinement: adding vendor copies of every Go source is inert.

    Given a baseline repository whose Go sources all sit at non-vendor
    paths, building an extended repository that adds a duplicate of
    every Go file under a ``vendor/dup/`` prefix MUST leave every
    detection list and the ``degraded_sections`` list of the produced
    :class:`ProjectProfile` unchanged. This is task 11.7's optional
    formulation, "copying a non-vendor file under ``vendor/``
    produces no additional detection".

    Because vendored files are rejected before reaching the tokenizer
    (:func:`is_go_source_file` is the single filter the parser
    consults), the extended repository's parser sees a file mapping
    identical to the baseline's. The four sub-analyzers therefore
    receive identical inputs and the four detection lists are
    identical by construction; ``degraded_sections`` is identical for
    the same reason — vendored files cannot trigger a
    ``SkipFileEvent`` from the parser layer.

    Only the four detection lists and the ``degraded_sections`` list
    are compared. ``produced_at`` differs across calls (analyze stamps
    each invocation with :func:`datetime.now`) and ``purpose_summary``
    is unaffected by vendor copies in principle but is excluded from
    the comparison because the purpose summarizer's candidate
    interleaving is exercised by Property 4
    (:mod:`tests.property.test_property_04_go_purpose_priority`).
    """

    base_profile = _run_analyze(base_files)

    extended_files = dict(base_files)
    for path, content in base_files.items():
        # Only Go files are subject to the vendor predicate; non-Go
        # files (which the strategy does not generate today, but
        # which a future generator extension might) would not change
        # detections regardless of placement.
        if path.endswith(".go"):
            extended_files[f"vendor/dup/{path}"] = content
    extended_profile = _run_analyze(extended_files)

    # Detection sets compare equal under Pydantic's value-equality
    # rule (frozen ``_FrozenModel`` subclasses define ``__eq__`` over
    # all fields), so list equality is exact set+order equality. The
    # aggregator produces detections in a deterministic order that is
    # a function of the file mapping alone (Requirement 11.4), so
    # adding vendor files cannot perturb the order either.
    assert base_profile.abstract_inputs == extended_profile.abstract_inputs, (
        "abstract_inputs differs after adding vendor copies; vendor "
        "files must not contribute detections (Requirement 1.3)"
    )
    assert base_profile.abstract_outputs == extended_profile.abstract_outputs, (
        "abstract_outputs differs after adding vendor copies; vendor "
        "files must not contribute detections (Requirement 1.3)"
    )
    assert (
        base_profile.external_service_dependencies
        == extended_profile.external_service_dependencies
    ), (
        "external_service_dependencies differs after adding vendor "
        "copies; vendor files must not contribute detections "
        "(Requirement 1.3)"
    )
    assert (
        base_profile.database_table_dependencies
        == extended_profile.database_table_dependencies
    ), (
        "database_table_dependencies differs after adding vendor "
        "copies; vendor files must not contribute detections "
        "(Requirement 1.3)"
    )

    # ``degraded_sections`` covers per-file skip strings (build
    # constraint, cgo, tokenization failure) appended by the four
    # ``_safe_*`` helpers. Vendored files are rejected before
    # reaching the parser, so no additional skip strings can appear
    # in the extended analysis; this assertion pins that contract.
    assert base_profile.degraded_sections == extended_profile.degraded_sections, (
        "degraded_sections differs after adding vendor copies; "
        "vendored files must not reach the parser (Requirement 1.3)"
    )
